export const gameCategories = [
  // Generos
  { value: "mmo", label: "MMO", group: "genre" },
  { value: "mmorpg", label: "MMORPG", group: "genre" },
  { value: "shooter", label: "Shooter", group: "genre" },
  { value: "strategy", label: "Strategy", group: "genre" },
  { value: "moba", label: "MOBA", group: "genre" },
  { value: "card", label: "Card Games", group: "genre" },
  { value: "racing", label: "Racing", group: "genre" },
  { value: "sports", label: "Sports", group: "genre" },
  { value: "social", label: "Social", group: "genre" },
  { value: "fighting", label: "Fighting", group: "genre" },

  // Tags
  { value: "mmofps", label: "MMOFPS", group: "tag" },
  { value: "action-rpg", label: "Action RPG", group: "tag" },
  { value: "sandbox", label: "Sandbox", group: "tag" },
  { value: "open-world", label: "Open World", group: "tag" },
  { value: "survival", label: "Survival", group: "tag" },
  { value: "battle-royale", label: "Battle Royale", group: "tag" },
  { value: "mmotps", label: "MMOTPS", group: "tag" },
  { value: "anime", label: "Anime", group: "tag" },
  { value: "pvp", label: "PvP", group: "tag" },
  { value: "pve", label: "PvE", group: "tag" },
  { value: "pixel", label: "Pixel", group: "tag" },
  { value: "mmorts", label: "MMORTS", group: "tag" },
  { value: "fantasy", label: "Fantasy", group: "tag" },
  { value: "sci-fi", label: "Sci-Fi", group: "tag" },
  { value: "action", label: "Action", group: "tag" },
  { value: "voxel", label: "Voxel", group: "tag" },
  { value: "zombie", label: "Zombie", group: "tag" },
  { value: "turn-based", label: "Turn-Based", group: "tag" },
  { value: "first-person", label: "First Person View", group: "tag" },
  { value: "third-person", label: "Third Person View", group: "tag" },
  { value: "top-down", label: "Top-Down View", group: "tag" },
  { value: "3d", label: "3D Graphics", group: "tag" },
  { value: "2d", label: "2D Graphics", group: "tag" },
  { value: "tank", label: "Tank", group: "tag" },
  { value: "space", label: "Space", group: "tag" },
  { value: "sailing", label: "Sailing", group: "tag" },
  { value: "side-scroller", label: "Side Scroller", group: "tag" },
  { value: "superhero", label: "Superhero", group: "tag" },
  { value: "permadeath", label: "Permadeath", group: "tag" },
];